from pydantic import BaseModel, Field
from typing import Dict, List, Any, Optional

class APIResponse(BaseModel):
    """
    Standardized API response format for all Stock Intelligence Platform endpoints.
    """
    success: bool = Field(..., description="Whether the operation succeeded.")
    execution_time: float = Field(..., description="Total execution time in seconds.")
    agent_used: Optional[str] = Field(None, description="The specialized agent that handled the request.")
    agent_plan: Optional[str] = Field(None, description="The step-by-step reasoning plan generated by the agent.")
    summary: str = Field(..., description="Natural language narrative summary of the results.")
    insights: List[str] = Field(default_factory=list, description="High-level insights extracted by the agent.")
    structured_data: Dict[str, Any] = Field(default_factory=dict, description="Deterministic calculations and metadata.")

class ChatRequest(BaseModel):
    """
    Request model for the general chat assistant endpoint.
    """
    message: str = Field(..., description="The query or command from the user.")
    session_id: Optional[str] = Field(None, description="Optional unique identifier for tracing.")

class AgentResponseFormat(BaseModel):
    """
    Structured response format for specialized worker agents.
    """
    summary: str = Field(..., description="Clean markdown report summary. Do NOT wrap it in ```markdown fences. Do NOT include placeholders like {{current_date}}, ReAct reasoning, thoughts, raw tool logs, or an insights section.")
    observations: List[str] = Field(..., description="A list of 3 to 5 key financial observations, warnings, or insights. Do not prefix items with bullets.")
