from typing import TypedDict, List, Dict, Any, Optional, TYPE_CHECKING

if TYPE_CHECKING:
    from app.observability.tracer import AgentTracer

class State(TypedDict):
    """
    State representing the context of the Stock Intelligence Platform graph.
    """
    uploaded_file: Optional[str]          # Local file path of the uploaded Excel sheet
    mapping_plan: Optional[Dict[str, Any]] # Mapped columns schema generated by LLM
    portfolio_dataframe: Optional[List[Dict[str, Any]]]  # Normalized transaction records
    holding_timeline: Optional[List[Dict[str, Any]]]     # Chronological holdings ledger
    selected_agent: Optional[str]          # The agent name routed by the supervisor
    messages: List[Any]                    # Conversation messages
    result: Optional[Dict[str, Any]]       # Final structured response
    errors: List[str]                      # Error log messages
    # ── Observability & Auth context ──────────────────────────────────────────
    tracer: Optional[Any]                  # AgentTracer instance (Any to avoid circular import)
    user_id: Optional[str]                 # Authenticated user ID
    session_id: Optional[str]             # Chat session ID
